"""make_user_name_nullable

Revision ID: 1b5b78797472
Revises: be6406c2a3e5
Create Date: 2026-01-12 00:13:00.829979

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b5b78797472"
down_revision: Union[str, None] = "be6406c2a3e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=30), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=30), nullable=False)
    # ### end Alembic commands ###
